server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: re-shopping-cart-web-app

  profiles:
    # active: prod # Production development
    active: local # Local development

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/defaultdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:false}

  thymeleaf:
    cache: ${THYMELEAF_CACHE:false}
